// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnchorReq struct {
	SeqFrom uint64 `json:"seqFrom,optional"`
	SeqTo   uint64 `json:"seqTo,optional"`
}

type AnchorResp struct {
	LedgerId string `json:"ledgerId"`
	Seq      uint64 `json:"seq"`
	Root     string `json:"root"`
	TxHash   string `json:"txHash,omitempty"`
	Status   string `json:"status"`
}

type AppendEntryReq struct {
	Entry EntryReq `json:"entry"`
}

type CreateLedgerReq struct {
	Type        string         `json:"type"`
	Name        string         `json:"name"`
	CreatorId   string         `json:"creatorId"`
	Members     []Member       `json:"members"`
	EntrySchema EntrySchemaReq `json:"entrySchema,optional"`
}

type EntrySchemaReq struct {
	TemplateId string         `json:"templateId,optional"`
	Fields     []EntryFieldDef `json:"fields,optional"`
}

type EntrySchemaResp struct {
	TemplateId string          `json:"templateId,omitempty"`
	Fields     []EntryFieldDef `json:"fields"`
}

type EntryFieldDef struct {
	Key      string `json:"key"`
	Label    string `json:"label"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
}

type EntryReq struct {
	SignerId string            `json:"signerId,optional"`
	SchemaId string            `json:"schemaId,optional"`
	Data     map[string]string `json:"data,optional"`
	Date     string            `json:"date,optional"`
	Type     string            `json:"type,optional"`
	Amount   string            `json:"amount,optional"`
	Category string            `json:"category,optional"`
	Note     string            `json:"note,optional"`
}

type EventResp struct {
	Seq       uint64 `json:"seq"`
	Type      string `json:"type"`
	Hash      string `json:"hash"`
	SignerId  string `json:"signerId,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type HealthResp struct {
	Status           string `json:"status"`
	MiniLedgerOnline bool   `json:"miniLedgerOnline"`
	IPFSOnline       bool   `json:"ipfsOnline"`
}

type LedgerResp struct {
	Id            string          `json:"id"`
	Type          string          `json:"type"`
	Name          string          `json:"name"`
	CreatorId     string          `json:"creatorId"`
	LedgerAddress string          `json:"ledgerAddress,omitempty"`
	Members       []Member        `json:"members"`
	EntrySchema   EntrySchemaResp `json:"entrySchema"`
	LatestSeq      uint64 `json:"latestSeq"`
	LatestRoot     string `json:"latestRoot"`
	BlockHeight    uint64 `json:"blockHeight,omitempty"`
	AnchorStatus   string `json:"anchorStatus"`
	LastBackupRef  string `json:"lastBackupRef,omitempty"`
	LastBackupCid  string `json:"lastBackupCid,omitempty"`
}

type ListEventsReq struct {
	From uint64 `form:"from,optional"`
	To   uint64 `form:"to,optional"`
}

type Member struct {
	Id      string `json:"id"`
	Address string `json:"address"`
	Role    string `json:"role,optional"`
}

type VerifyResp struct {
	Valid bool `json:"valid"`
}
