// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/smart-ledger/go-smart-ledger/go-backend/pkg/router"
	"github.com/smart-ledger/go-smart-ledger/go-backend/services/ledger/internal/svc"
)

func RegisterHandlers(r router.Registrar, serverCtx *svc.ServiceContext) {
	r.Add(http.MethodGet, "/api/v1/health", healthHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/ledgers", createLedgerHandler(serverCtx))
	r.Add(http.MethodGet, "/api/v1/ledgers", listLedgersHandler(serverCtx))
	r.Add(http.MethodGet, "/api/v1/ledgers/:id", getLedgerHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/ledgers/:id/anchor", anchorLedgerHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/ledgers/:id/entries", appendEntryHandler(serverCtx))
	r.Add(http.MethodGet, "/api/v1/ledgers/:id/events", listEventsHandler(serverCtx))
	r.Add(http.MethodGet, "/api/v1/ledgers/:id/verify", verifyLedgerHandler(serverCtx))
}
