// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnchorReq struct {
	SeqFrom uint64 `json:"seqFrom,optional"`
	SeqTo   uint64 `json:"seqTo,optional"`
}

type AnchorResp struct {
	LedgerId            string               `json:"ledgerId"`
	Seq                 uint64               `json:"seq"`
	Root                string               `json:"root"`
	TxHash              string               `json:"txHash,omitempty"`
	Status              string               `json:"status"`
	ExternalAnchor      *ExternalAnchorResp  `json:"externalAnchor,omitempty"`
}

type ExternalAnchorResp struct {
	TxHash      string `json:"txHash"`
	ChainId     uint64 `json:"chainId"`
	ChainName   string `json:"chainName,omitempty"`
	ExplorerUrl string `json:"explorerUrl,omitempty"`
	MerkleRoot  string `json:"merkleRoot,omitempty"`
}

type AppendEntryReq struct {
	Entry EntryReq `json:"entry"`
}

type ApprovalPolicyReq struct {
	Enabled   bool `json:"enabled,optional"`
	Threshold int  `json:"threshold,optional"`
}

type EncryptionReq struct {
	Enabled               bool              `json:"enabled,optional"`
	Algo                  string            `json:"algo,optional"`
	WrappedKeys           map[string]string `json:"wrappedKeys,optional"`
	PassphraseViewEnabled bool              `json:"passphraseViewEnabled,optional"`
	PassphraseWrappedKeys map[string]string `json:"passphraseWrappedKeys,optional"`
}

type CreateLedgerReq struct {
	Type              string            `json:"type"`
	Name              string            `json:"name"`
	CreatorId         string            `json:"creatorId"`
	Members           []Member          `json:"members"`
	BookkeepingMode   string            `json:"bookkeepingMode,optional"`
	EntrySchema       EntrySchemaReq    `json:"entrySchema,optional"`
	MultiTableEnabled bool              `json:"multiTableEnabled,optional"`
	ApprovalPolicy    ApprovalPolicyReq `json:"approvalPolicy,optional"`
	Encryption        EncryptionReq     `json:"encryption,optional"`
	StorageLocation   string            `json:"storageLocation,optional"`
}

type EntrySchemaReq struct {
	TemplateId string         `json:"templateId,optional"`
	Fields     []EntryFieldDef `json:"fields,optional"`
}

type EntrySchemaResp struct {
	TemplateId string          `json:"templateId,omitempty"`
	Fields     []EntryFieldDef `json:"fields"`
}

type LedgerTableResp struct {
	Id          string          `json:"id"`
	Name        string          `json:"name"`
	EntrySchema EntrySchemaResp `json:"entrySchema"`
	SortOrder   int             `json:"sortOrder"`
	RowOrder    []uint64        `json:"rowOrder,omitempty"`
	CreatedAt   string          `json:"createdAt,omitempty"`
}

type EntryFieldDef struct {
	Key      string `json:"key"`
	Label    string `json:"label"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
}

type EntryReq struct {
	SignerId string            `json:"signerId,optional"`
	TableId  string            `json:"tableId,optional"`
	SchemaId string            `json:"schemaId,optional"`
	Data     map[string]string `json:"data,optional"`
	Date     string            `json:"date,optional"`
	Type     string            `json:"type,optional"`
	Amount   string            `json:"amount,optional"`
	Category string            `json:"category,optional"`
	Note     string            `json:"note,optional"`
}

type EventResp struct {
	Seq       uint64 `json:"seq"`
	Type      string `json:"type"`
	Hash      string `json:"hash"`
	SignerId  string `json:"signerId,omitempty"`
	CreatedAt string `json:"createdAt"`
	Payload   any    `json:"payload,omitempty"`
}

type HealthResp struct {
	Status           string `json:"status"`
	MiniLedgerOnline bool   `json:"miniLedgerOnline"`
	IPFSOnline       bool   `json:"ipfsOnline"`
	QueuePending     int    `json:"queuePending,omitempty"`
	QueueFailed      int    `json:"queueFailed,omitempty"`
}

type LedgerResp struct {
	Id             string            `json:"id"`
	Type           string            `json:"type"`
	Name           string            `json:"name"`
	CreatorId      string            `json:"creatorId"`
	LedgerAddress  string            `json:"ledgerAddress,omitempty"`
	Members          []Member          `json:"members"`
	BookkeepingMode  string            `json:"bookkeepingMode,omitempty"`
	MultiTableEnabled bool              `json:"multiTableEnabled,omitempty"`
	Tables            []LedgerTableResp `json:"tables,omitempty"`
	EntrySchema       EntrySchemaResp   `json:"entrySchema"`
	ApprovalPolicy ApprovalPolicyReq `json:"approvalPolicy,omitempty"`
	Encryption     EncryptionReq     `json:"encryption,omitempty"`
	LatestSeq      uint64            `json:"latestSeq"`
	LatestRoot     string            `json:"latestRoot"`
	BlockHeight    uint64            `json:"blockHeight,omitempty"`
	AnchorStatus     string               `json:"anchorStatus"`
	ExternalAnchor   *ExternalAnchorResp  `json:"externalAnchor,omitempty"`
	LastBackupRef     string               `json:"lastBackupRef,omitempty"`
	LastBackupCid     string               `json:"lastBackupCid,omitempty"`
	StorageLocation   string               `json:"storageLocation,omitempty"`
	CreatedAt         string               `json:"createdAt,omitempty"`
	UpdatedAt         string               `json:"updatedAt,omitempty"`
}

type SetStorageLocationReq struct {
	StorageLocation string `json:"storageLocation"`
}

type ListEventsReq struct {
	From uint64 `form:"from,optional"`
	To   uint64 `form:"to,optional"`
}

type Member struct {
	Id      string `json:"id"`
	Address string `json:"address"`
	Role    string `json:"role,optional"`
}

type VerifyResp struct {
	Valid bool `json:"valid"`
}
