// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResp struct {
	Status            string `json:"status"`
	Gateway           string `json:"gateway"`
	MiniLedgerOnline  bool   `json:"miniLedgerOnline"`
	ChainQueuePending int    `json:"chainQueuePending,omitempty"`
	ChainQueueFailed  int    `json:"chainQueueFailed,omitempty"`
}
