// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CaptchaResp struct {
	CaptchaId string `json:"captchaId"`
	Image     string `json:"image"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type LoginReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	CaptchaId   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type LoginResp struct {
	AccessToken string   `json:"accessToken"`
	ExpiresIn   int64    `json:"expiresIn"`
	TokenType   string   `json:"tokenType"`
	User        UserInfo `json:"user"`
}

type RefreshResp struct {
	AccessToken string   `json:"accessToken"`
	ExpiresIn   int64    `json:"expiresIn"`
	TokenType   string   `json:"tokenType"`
	User        UserInfo `json:"user"`
}

type UserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
}
