// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/smart-ledger/go-smart-ledger/go-backend/pkg/router"
	"github.com/smart-ledger/go-smart-ledger/go-backend/services/storage/internal/svc"
)

func RegisterHandlers(r router.Registrar, serverCtx *svc.ServiceContext) {
	r.Add(http.MethodPost, "/api/v1/storage/backup", putBackupHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/storage/backup/fetch", getBackupHandler(serverCtx))
	r.Add(http.MethodGet, "/api/v1/storage/health", healthHandler(serverCtx))
}
