// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/smart-ledger/go-smart-ledger/go-backend/pkg/router"
	"github.com/smart-ledger/go-smart-ledger/go-backend/services/auth/internal/svc"
)

func RegisterHandlers(r router.Registrar, serverCtx *svc.ServiceContext) {
	r.Add(http.MethodGet, "/api/v1/auth/captcha", captchaHandler(serverCtx))
	r.Add(http.MethodGet, "/api/v1/auth/health", healthHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/auth/login", loginHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/auth/logout", logoutHandler(serverCtx))
	r.Add(http.MethodPost, "/api/v1/auth/refresh", refreshHandler(serverCtx))
}
