Name: ledger-api
Host: 0.0.0.0
Port: 28888

MiniLedger:
  BaseURL: http://miniledger:24441

BackupDir: /data/backups

HDWallet:
  Mnemonic: "test test test test test test test test test test test junk"

Snowflake:
  NodeID: 2

IPFS:
  ApiURL: http://ipfs:5001
  Enabled: false

Log:
  Mode: console
  Level: info
