FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /storage-api ./services/storage

FROM alpine:3.20
WORKDIR /app
COPY --from=build /storage-api .
COPY deploy/etc/storage-api.docker.yaml etc/storage-api.yaml
RUN mkdir -p /data/backups
EXPOSE 8890
CMD ["./storage-api", "-f", "etc/storage-api.yaml"]
