FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /gateway-api ./services/gateway

FROM alpine:3.20
WORKDIR /app
COPY --from=build /gateway-api .
COPY deploy/etc/gateway-api.docker.yaml etc/gateway-api.yaml
EXPOSE 8080
CMD ["./gateway-api", "-f", "etc/gateway-api.yaml"]
