FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /ledger-api ./services/ledger

FROM alpine:3.20
WORKDIR /app
COPY --from=build /ledger-api .
COPY deploy/etc/ledger-api.docker.yaml etc/ledger-api.yaml
EXPOSE 8888
CMD ["./ledger-api", "-f", "etc/ledger-api.yaml"]
