server:
  port: 28887

spring:
  application:
    name: auth-api

smartledger:
  jwt:
    access-secret: smart-ledger-access-secret-change-me
    refresh-secret: smart-ledger-refresh-secret-change-me
    access-expire-seconds: 900
    refresh-expire-seconds: 604800
    cookie-secure: false

logging:
  level:
    root: info
