// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetBackupReq struct {
	Ref      string `json:"ref"`
	Password string `json:"password"`
}

type GetBackupResp struct {
	Payload string `json:"payload"` // base64
}

type HealthResp struct {
	Status string `json:"status"`
}

type PutBackupReq struct {
	LedgerId string `json:"ledgerId"`
	Password string `json:"password"`
	Payload  string `json:"payload"` // base64
}

type PutBackupResp struct {
	Ref string `json:"ref"`
}
